### ISSUE TITLE
[BUG] no levels or ratings

### ISSUE THREAD

**Issue by FoxivanFable** [eternalUnion/AngryLevelLoader#27] opened 2024-08-26 23:59 UTC
# Description
no updates or new levels are showing up, and the ratings are all 0

# Plugins Used
* too many to type

# Console Logs
If you have any errors or warnings on the bepinex console, log below. (How to open the console: https://docs.bepinex.dev/articles/user_guide/troubleshooting.html)
```
[Info   :AngryLevelLoader] Current online level catalog is up to date, loading from cache
[Info   :AngryLevelLoader] Cached script catalog up to date
[Error  :AngryLevelLoader] Could not get all votes while refreshing. Message: . Status: FAILED.
```

# Extras
Anything you want to add

**Comment by eternalUnion** [comment] 2024-08-27 06:24
Duplicate of #26, server and new levels coming soon

**Closed as not planned** 2024-08-27 06:24 UTC
Labels: bug
